### ISSUE TITLE
duo-ls(1): only works with a component.json

### ISSUE THREAD

**Issue by matthewmueller** [duojs/duo#186]
Right now it show entries as a component. It should show entries by filename

``` bash
$ duo ls

   error : Error: ENOENT, no such file or directory '/Users/matt/Projects/duo/examples/module/component.json'
    at Error (native)
    at Object.fs.openSync (fs.js:443:18)
    at Object.fs.readFileSync (fs.js:309:15)
    at read (/Users/matt/Projects/duo/bin/duo-ls:155:13)
    at Object.<anonymous> (/Users/matt/Projects/duo/bin/duo-ls:69:30)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Function.Module.runMain (module.js:490:10)
```

/cc @yields

**Comment by michaeltroy** [comment]
Hey guys,

Was this resolved? I'm seeing this error with Duo 0.9.6.
