### ISSUE TITLE
Error: Command failed: Username for 'https://github.com':

### ISSUE THREAD

**Issue by dy** [duojs/duo#397]
I’m trying to `duo index.css > bundle.css`, then it shows:

```
     building : index.css
        error : Error: Command failed: Username for 'https://github.com':
fatal: could not read Username for 'https://github.com': No such file or directory

    at error (c:\Users\dmitry\AppData\Roaming\npm\node_modules\duo\node_modules\duo-package\node_modules\gh-resolve\index.js:177:10)
    at c:\Users\dmitry\AppData\Roaming\npm\node_modules\duo\node_modules\duo-package\node_modules\gh-resolve\index.js:69:37
    at ChildProcess.exithandler (child_process.js:641:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Socket.<anonymous> (child_process.js:956:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

I use windows 7.

I have a `_netrc` set up with github token in `%HOME%` dir. How else can I help the situation?

**Comment by dominicbarnes** [comment]
I know it's a little late to ask, but what does `index.css` look like?

**Comment by dfcreative** [comment]
@dominicbarnes some entry `index.css` with inner `@import` directives, I guess.
