### ISSUE TITLE
file such as `example.js.js` won't load

### ISSUE THREAD

**Issue by lancejpollard** [duojs/duo#420]
If you have a file named:

```
example.js.js
```

And you try to require it with this:

```js
var exampleJS = require('./example.js');
```

It will error on download:

```
    installed : ianstormtaylor-is@0.1.1
        error : Error: Command failed: /bin/sh -c git ls-remote --tags --heads https://<token>@github.com/libraries/analytics.js
remote: Repository not found.
fatal: repository 'https://<token>@github.com/libraries/analytics.js/' not found

    at error (/Users/lancejpollard/hacks/h96/node_modules/duo/node_modules/duo-package/node_modules/gh-resolve/index.js:177:10)
    at /Users/lancejpollard/hacks/h96/node_modules/duo/node_modules/duo-package/node_modules/gh-resolve/index.js:69:37
    at ChildProcess.exithandler (child_process.js:736:5)
    at ChildProcess.EventEmitter.emit (events.js:110:17)
    at maybeClose (child_process.js:992:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1059:5)
```

**Comment by dominicbarnes** [comment]
I'm looking into this right now, but I have noticed that if you use the (albeit _uglify_) `./example.js.js`, then it does work as expected.
